/**
 * Central Font Awesome icon definitions for the merchant panel.
 */
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowTrendUp,
  faBolt,
  faBookOpen,
  faBullseye,
  faCaretDown,
  faCaretUp,
  faChartBar,
  faChartLine,
  faCheck,
  faChevronLeft,
  faCircleCheck,
  faCircleXmark,
  faComments,
  faCrown,
  faFire,
  faGear,
  faHandshake,
  faHouse,
  faLocationDot,
  faLock,
  faMoneyBillTransfer,
  faPhone,
  faPlus,
  faRotate,
  faShieldHalved,
  faStore,
  faTag,
  faTags,
  faTrophy,
  faUser,
  faUserSlash,
  faUsers,
  faXmark,
  faBan,
  faClipboardCheck,
  faRightFromBracket,
  faCircleInfo,
  faReceipt,
  faRocket,
  faSkull,
  faCircle,
} from "@fortawesome/free-solid-svg-icons";

export {
  faArrowTrendUp,
  faBolt,
  faBookOpen,
  faBullseye,
  faCaretDown,
  faCaretUp,
  faChartBar,
  faChartLine,
  faCheck,
  faChevronLeft,
  faCircleCheck,
  faCircleXmark,
  faComments,
  faCrown,
  faFire,
  faGear,
  faHandshake,
  faHouse,
  faLocationDot,
  faLock,
  faMoneyBillTransfer,
  faPhone,
  faPlus,
  faRotate,
  faShieldHalved,
  faStore,
  faTag,
  faTags,
  faTrophy,
  faUser,
  faUserSlash,
  faUsers,
  faXmark,
  faBan,
  faClipboardCheck,
  faRightFromBracket,
  faCircleInfo,
  faReceipt,
  faRocket,
  faSkull,
  faCircle,
};

/** News feed event → icon (API may still send emoji strings; we prefer these). */
export const NEWS_FEED_EVENT_ICONS: Record<string, IconDefinition> = {
  created: faPlus,
  updated: faCircleInfo,
  deleted: faXmark,
  scanned: faClipboardCheck,
  approved: faCircleCheck,
  rejected: faCircleXmark,
};

export function newsFeedIcon(event: string, fallback?: string): IconDefinition {
  if (NEWS_FEED_EVENT_ICONS[event]) return NEWS_FEED_EVENT_ICONS[event];
  if (fallback && NEWS_FEED_EVENT_ICONS[fallback]) return NEWS_FEED_EVENT_ICONS[fallback];
  return faBolt;
}
