/**
 * Central Font Awesome icon definitions for the merchant panel.
 */
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowTrendUp,
  faBolt,
  faBookOpen,
  faBullseye,
  faCalendarDay,
  faCaretDown,
  faCaretUp,
  faChartBar,
  faChartLine,
  faCheck,
  faChevronLeft,
  faCircleCheck,
  faCircleXmark,
  faComments,
  faCrown,
  faEnvelope,
  faFire,
  faFlask,
  faGear,
  faHandshake,
  faHouse,
  faKey,
  faLocationDot,
  faLock,
  faMobileScreen,
  faMoneyBillTransfer,
  faPaperPlane,
  faPenToSquare,
  faPhone,
  faPlus,
  faRotate,
  faShieldHalved,
  faStore,
  faTag,
  faTags,
  faTrophy,
  faUser,
  faUserSlash,
  faUsers,
  faXmark,
  faBan,
  faClipboardCheck,
  faRightFromBracket,
  faCircleInfo,
  faReceipt,
  faRocket,
  faSkull,
  faCircle,
} from "@fortawesome/free-solid-svg-icons";

export {
  faArrowTrendUp,
  faBolt,
  faBookOpen,
  faBullseye,
  faCalendarDay,
  faCaretDown,
  faCaretUp,
  faChartBar,
  faChartLine,
  faCheck,
  faChevronLeft,
  faCircleCheck,
  faCircleXmark,
  faComments,
  faCrown,
  faEnvelope,
  faFire,
  faFlask,
  faGear,
  faKey,
  faHandshake,
  faHouse,
  faLocationDot,
  faLock,
  faMobileScreen,
  faMoneyBillTransfer,
  faPaperPlane,
  faPenToSquare,
  faPhone,
  faPlus,
  faRotate,
  faShieldHalved,
  faStore,
  faTag,
  faTags,
  faTrophy,
  faUser,
  faUserSlash,
  faUsers,
  faXmark,
  faBan,
  faClipboardCheck,
  faRightFromBracket,
  faCircleInfo,
  faReceipt,
  faRocket,
  faSkull,
  faCircle,
};

/** News feed event → icon (API may still send emoji strings; we prefer these). */
export const NEWS_FEED_EVENT_ICONS: Record<string, IconDefinition> = {
  created: faPlus,
  updated: faCircleInfo,
  deleted: faXmark,
  scanned: faClipboardCheck,
  approved: faCircleCheck,
  rejected: faCircleXmark,
  merchant_submitted: faPenToSquare,
  onboarding_link_sent: faEnvelope,
  store_profile_completed: faClipboardCheck,
  password_reset: faKey,
  credentials_resent_email: faPaperPlane,
  credentials_resent_sms: faMobileScreen,
};

/** Legacy emoji icons from the API → Font Awesome. */
const NEWS_FEED_EMOJI_ICONS: Record<string, IconDefinition> = {
  "✨": faPlus,
  "✏️": faCircleInfo,
  "🗑️": faXmark,
  "📱": faClipboardCheck,
  "📝": faPenToSquare,
  "✅": faCircleCheck,
  "⛔": faCircleXmark,
  "✉️": faEnvelope,
  "📋": faClipboardCheck,
  "🔑": faKey,
  "📤": faPaperPlane,
  "⚡": faBolt,
};

export function newsFeedIcon(event: string, fallback?: string): IconDefinition {
  if (NEWS_FEED_EVENT_ICONS[event]) return NEWS_FEED_EVENT_ICONS[event];
  if (fallback && NEWS_FEED_EVENT_ICONS[fallback]) return NEWS_FEED_EVENT_ICONS[fallback];
  if (fallback && NEWS_FEED_EMOJI_ICONS[fallback]) return NEWS_FEED_EMOJI_ICONS[fallback];
  return faBolt;
}
