export type CommunityBuildCategory =
  | "Feed"
  | "Create"
  | "Teams"
  | "Rewards"
  | "Ranks"
  | "Chat"
  | "Wallet"
  | "Profile";

export type CommunityBuildScreen = {
  id: string;
  stitchScreenId: string;
  title: string;
  slug: string;
  category: CommunityBuildCategory;
  route: string;
  headline: string;
  summary: string;
  primaryAction: string;
  metrics: string[];
  sections: string[];
  apiActions: string[];
  integrationNotes: string[];
  qaChecks: string[];
  accent: "purple" | "yellow" | "orange" | "cyan";
};

export const COMMUNITY_BUILD_SCREENS: CommunityBuildScreen[] = [
  {
    id: "CB-01",
    stitchScreenId: "2bf3c1644d3c494687ad175e854c2930",
    title: "Community Feed",
    slug: "community-feed",
    category: "Feed",
    route: "/community/feed",
    headline: "Unified social arena for every merchant and squad.",
    summary: "A high-density feed with post cards, team stamps, author identity, engagement counters, and quick filters.",
    primaryAction: "Open feed",
    metrics: ["All/mine tabs", "Type filters", "Stamp earning actions"],
    sections: ["Hero scoreboard", "Post composer shortcut", "Filter rail", "Two-column feed cards"],
    apiActions: ["GET /community/feed", "POST /community/posts/{post}/like", "POST /community/posts/{post}/view"],
    integrationNotes: ["Use tab, type, tag, and area query params from Community Feed API.", "Engagement actions can award live reward stamps when the user has an active team."],
    qaChecks: ["Empty feed state is visible.", "Boosted and reported posts retain status chips.", "Mobile filter rail scrolls horizontally."],
    accent: "purple",
  },
  {
    id: "CB-02",
    stitchScreenId: "09beb900c24e45269596202f82d4c3db",
    title: "Community Feed: Unified Hub & Filters",
    slug: "community-feed-unified-hub",
    category: "Feed",
    route: "/community/feed?tab=all",
    headline: "Command-center feed with live filters and hype modules.",
    summary: "The Stitch hub version adds trend cards, feed type chips, leaderboard nudges, and recent stamp activity above the feed.",
    primaryAction: "Filter posts",
    metrics: ["Live reward banner", "Hot tags", "Boost alerts"],
    sections: ["Reward ticker", "Category pills", "Trending posts", "Team stamp recap"],
    apiActions: ["GET /community/feed?tab=all&type={type}", "GET /rewards/live", "GET /leaderboards/live-reward"],
    integrationNotes: ["Hydrate the reward banner from the live reward endpoint.", "Use feed filters without resetting scroll position."],
    qaChecks: ["Filter changes update query key.", "Reward banner hides when no reward is live.", "Long category labels do not wrap awkwardly."],
    accent: "yellow",
  },
  {
    id: "CB-03",
    stitchScreenId: "54076ed42b304b829615dec321e481a8",
    title: "Community Feed: Marketplace Example",
    slug: "community-feed-marketplace",
    category: "Feed",
    route: "/community/posts/[id]",
    headline: "Buy-sell cards with price, condition, proof media, and chat.",
    summary: "Marketplace posts emphasize price, condition, seller team, media preview, and a direct conversation CTA.",
    primaryAction: "Start marketplace chat",
    metrics: ["Price chip", "Seller team", "Chat conversion"],
    sections: ["Media carousel", "Listing details", "Seller proof", "Conversation CTA"],
    apiActions: ["POST /community/posts/{post}/conversations", "GET /community/conversations/{conversation}/messages", "POST /community/conversations/{conversation}/messages"],
    integrationNotes: ["Only marketplace and service request posts can open one-to-one conversations.", "Conversation realtime listens on private feed conversation channels."],
    qaChecks: ["CTA is hidden for non-marketplace posts.", "Unavailable listing states are disabled.", "Message send handles empty body validation."],
    accent: "orange",
  },
  {
    id: "CB-04",
    stitchScreenId: "db39443bd56545288173038f44c567ba",
    title: "Community Feed: Event Example",
    slug: "community-feed-event",
    category: "Feed",
    route: "/community/posts/[id]",
    headline: "Event posts built for RSVP-like discovery and local action.",
    summary: "Event cards surface time, location, area, team host, comments, and share actions in a stadium-style layout.",
    primaryAction: "Share event",
    metrics: ["Event time", "Location", "Shares"],
    sections: ["Event poster", "Location block", "Host team", "Comment stack"],
    apiActions: ["GET /community/posts/{post}", "POST /community/posts/{post}/share", "POST /community/posts/{post}/comments"],
    integrationNotes: ["Create events with event[event_at], event[ends_at], and event[location].", "Event posting fee flags come from Feed Parameters in admin."],
    qaChecks: ["Missing end time renders cleanly.", "Location line remains readable on mobile.", "Share count refreshes after action."],
    accent: "cyan",
  },
  {
    id: "CB-05",
    stitchScreenId: "e69234635bf94e02b99536c9b32ca42c",
    title: "Create Post: Update Tab",
    slug: "create-post-update",
    category: "Create",
    route: "/community/create?type=update",
    headline: "Fast update composer for team-visible announcements.",
    summary: "A tabbed post composer with title, body, tags, area, and media upload for normal community updates.",
    primaryAction: "Publish update",
    metrics: ["Title/body", "Tags", "Media"],
    sections: ["Type tabs", "Ghost inputs", "Tag chips", "Preview card"],
    apiActions: ["POST /community/posts"],
    integrationNotes: ["Send multipart type=update with title, body, area, tags[], and media[].", "Award create_update_stamps when configured."],
    qaChecks: ["Required fields block submit.", "Media uploads keep order.", "Successful publish routes back to feed."],
    accent: "purple",
  },
  {
    id: "CB-06",
    stitchScreenId: "16709927c2df4feb8d7a9c70618b4d65",
    title: "Create Post: Poll Tab",
    slug: "create-post-poll",
    category: "Create",
    route: "/community/create?type=poll",
    headline: "Poll composer for squad decisions and quick votes.",
    summary: "Poll form with question, dynamic options, multiple-choice toggle, close time, and reward stamp preview.",
    primaryAction: "Launch poll",
    metrics: ["Options", "Close time", "Vote rules"],
    sections: ["Poll question", "Option builder", "Multiple select toggle", "Expiry control"],
    apiActions: ["POST /community/posts", "POST /community/posts/{post}/poll/vote"],
    integrationNotes: ["Use poll[question], poll[options][], poll[allow_multiple], and poll[closes_at].", "Vote endpoint accepts option_ids and validates multiple selection rules."],
    qaChecks: ["At least two options required.", "Closed polls disable voting.", "Multiple-choice UI matches backend flag."],
    accent: "yellow",
  },
  {
    id: "CB-07",
    stitchScreenId: "18a8a31117094c03bbfdbca70c0c8d6d",
    title: "Create Post: Marketplace Tab",
    slug: "create-post-marketplace",
    category: "Create",
    route: "/community/create?type=marketplace",
    headline: "Marketplace composer with price, condition, media, and chat unlock.",
    summary: "A commerce-focused form that turns a community post into a marketplace listing with one-to-one chat enabled.",
    primaryAction: "List item",
    metrics: ["Price", "Condition", "Buyer chat"],
    sections: ["Listing basics", "Price panel", "Media dropzone", "Seller note"],
    apiActions: ["POST /community/posts", "POST /community/posts/{post}/conversations"],
    integrationNotes: ["Send marketplace[price], marketplace[currency], and marketplace[condition].", "Posting fee toggles can be controlled by marketplace_posting_fee_enabled."],
    qaChecks: ["Currency defaults to INR.", "Price accepts decimal values.", "Chat opens only after post creation."],
    accent: "orange",
  },
  {
    id: "CB-08",
    stitchScreenId: "b89e7cb5288f407da9d4fbabb0c27be1",
    title: "Create Flow: Dynamic Tabbed Forms",
    slug: "create-flow-dynamic-tabs",
    category: "Create",
    route: "/community/create",
    headline: "One composer, six post types, zero dead ends.",
    summary: "The master create flow switches between update, safety alert, poll, service request, marketplace, and event schemas.",
    primaryAction: "Create any post",
    metrics: ["6 post types", "Multipart payload", "Live validation"],
    sections: ["Type switcher", "Dynamic fields", "Reward preview", "Publish status"],
    apiActions: ["POST /community/posts"],
    integrationNotes: ["Build payloads from the type-specific field map in Community Feed API.", "Use the same submit path and vary nested form keys by type."],
    qaChecks: ["Switching tabs preserves common fields.", "Type-specific errors are scoped.", "Draft reset is explicit."],
    accent: "cyan",
  },
  {
    id: "CB-09",
    stitchScreenId: "6229b0ecdec345fab06e4474a66d8b35",
    title: "Team Hub: Grow Squad & Actions Integrated",
    slug: "team-hub",
    category: "Teams",
    route: "/community-build/team-hub",
    headline: "Squad control room for members, invites, requests, and live reward status.",
    summary: "A merchant-facing team hub showing active membership, team code, invite actions, join requests, and reward eligibility.",
    primaryAction: "Manage squad",
    metrics: ["Team code", "Member count", "Pending joins"],
    sections: ["Squad identity", "Invite panel", "Member roster", "Eligibility checklist"],
    apiActions: ["GET /teams/mine", "GET /teams/{team}", "POST /teams/{team}/invite", "GET /teams/{team}/join-requests"],
    integrationNotes: ["Team admins can approve or reject join requests.", "Reward join is blocked until min_team_members is met."],
    qaChecks: ["No-team state links to create/join.", "Admin-only actions are hidden for members.", "Invite token copy gives confirmation."],
    accent: "purple",
  },
  {
    id: "CB-10",
    stitchScreenId: "d144f62b0c9b4e4db4aea8fa678a837f",
    title: "Create Team: Identity & Setup",
    slug: "create-team",
    category: "Teams",
    route: "/community-build/create-team",
    headline: "Create a reward squad with a bold identity and unique team code.",
    summary: "Setup form for squad name, description, confirmation, and immediate admin ownership state.",
    primaryAction: "Create team",
    metrics: ["Unique name", "Admin role", "Team code"],
    sections: ["Name card", "Description", "Rules panel", "Success state"],
    apiActions: ["POST /teams", "GET /teams/mine"],
    integrationNotes: ["Backend prevents creating a team when the user already has active membership.", "Creator becomes team admin automatically."],
    qaChecks: ["Duplicate names show validation.", "Existing members cannot create another team.", "Success routes to team hub."],
    accent: "yellow",
  },
  {
    id: "CB-11",
    stitchScreenId: "02e2f175d7f241ef812cf89f0641e252",
    title: "Join Team: Search & Request Integrated",
    slug: "join-team-search-request",
    category: "Teams",
    route: "/community-build/join-team",
    headline: "Find a squad by name or code and request entry.",
    summary: "Search results with team stats, request state, and the switch-team warning required by backend rules.",
    primaryAction: "Request join",
    metrics: ["Name/code search", "Pending state", "Switch warning"],
    sections: ["Search bar", "Result cards", "Request modal", "Status receipt"],
    apiActions: ["GET /teams/search?name={query}", "POST /teams/join"],
    integrationNotes: ["Join body may send code or team_name.", "Approval can move the user out of a previous team and notify the previous admin."],
    qaChecks: ["Empty search prompts code entry.", "Duplicate pending request is explained.", "Switch confirmation copy uses squad terminology."],
    accent: "orange",
  },
  {
    id: "CB-12",
    stitchScreenId: "31c7d8d35cfa4af7a9d9848f3a4c515f",
    title: "Join Team: Switch Confirmation Terminology Update",
    slug: "join-team-switch-confirmation",
    category: "Teams",
    route: "/community-build/join-team/switch",
    headline: "Clear confirmation when joining means leaving another squad.",
    summary: "A focused confirmation screen that explains membership transfer, admin notification, and pending request state.",
    primaryAction: "Confirm switch request",
    metrics: ["Current squad", "Target squad", "Admin notification"],
    sections: ["Risk banner", "Squad comparison", "Confirm CTA", "Cancel escape"],
    apiActions: ["POST /teams/join"],
    integrationNotes: ["The backend exits the previous team only after the target admin approves the request.", "FCM notifies affected admins."],
    qaChecks: ["Copy is explicit about request vs immediate switch.", "Cancel returns to search.", "Pending request cannot be submitted twice."],
    accent: "cyan",
  },
  {
    id: "CB-13",
    stitchScreenId: "34d9ea89ba52476d9830751dfb15a74e",
    title: "Reward Hub: Participation Requirements Refined",
    slug: "reward-hub",
    category: "Rewards",
    route: "/community/rewards",
    headline: "Live reward lobby with team requirements and task flash cards.",
    summary: "Reward overview with countdown, worth value, stamps left, team eligibility, join CTA, and task cards.",
    primaryAction: "Join live reward",
    metrics: ["Countdown", "Stamps left", "Worth value"],
    sections: ["Live reward hero", "Participation rules", "Task grid", "Submission state"],
    apiActions: ["GET /rewards/live", "POST /rewards/{reward}/join", "GET /rewards/{reward}/tasks", "POST /rewards/{reward}/tasks/{task}/submit"],
    integrationNotes: ["Join requires active team and minimum team members.", "Task type controls fields and verification mode."],
    qaChecks: ["No live reward state exists.", "Join button handles 422 rule failures.", "Task submissions refresh stamps."],
    accent: "yellow",
  },
  {
    id: "CB-14",
    stitchScreenId: "4e218db9ac38439388d55ca231e647a2",
    title: "Task Hub: Enhanced Countdown & Leaderboard Push",
    slug: "task-hub-countdown",
    category: "Rewards",
    route: "/community/rewards",
    headline: "Flash-card task board with urgent countdown and leaderboard pressure.",
    summary: "Task hub surfaces pending cards, auto/manual verification, proof upload, and live leaderboard movement.",
    primaryAction: "Submit task",
    metrics: ["Pending cards", "Verification mode", "Rank push"],
    sections: ["Countdown strip", "Task cards", "Proof drawer", "Leaderboard nudge"],
    apiActions: ["GET /rewards/{reward}/tasks", "POST /rewards/{reward}/tasks/{task}/submit", "GET /leaderboards/live-reward"],
    integrationNotes: ["Multipart submissions include proof_text, payload fields, and proof[] files.", "Auto-verified tasks award stamps immediately."],
    qaChecks: ["File fields use multipart.", "Manual review state is visible.", "Auto verification result is displayed."],
    accent: "orange",
  },
  {
    id: "CB-15",
    stitchScreenId: "c885e34dd24a48fdbd1f6cf507d5e5d5",
    title: "Task Hub: Individual Rank Boost State",
    slug: "task-hub-rank-boost",
    category: "Rewards",
    route: "/community/rewards",
    headline: "Personal boost state for users chasing weekly member rank.",
    summary: "A task variant that highlights individual contribution, weekly member rank, and next stamp milestone.",
    primaryAction: "Boost my rank",
    metrics: ["My stamps", "Next rank", "Task streak"],
    sections: ["Personal rank card", "Milestone bar", "Suggested task", "Reward proof"],
    apiActions: ["GET /leaderboards/weekly-members", "GET /rewards/{reward}/my-submissions", "GET /rewards/my-stamps"],
    integrationNotes: ["Weekly member leaderboard ranks individual users by current week reward stamps.", "Submissions endpoint returns status and awarded stamps."],
    qaChecks: ["User absent from leaderboard shows join prompt.", "Rejected submissions show reason.", "Milestone math handles zero stamps."],
    accent: "purple",
  },
  {
    id: "CB-16",
    stitchScreenId: "7cdc883875864b1ca0329b93bfff673f",
    title: "Hall of Fame: Weekly Rewards Integrated",
    slug: "hall-of-fame",
    category: "Ranks",
    route: "/community/leaderboards",
    headline: "Completed rewards, winners, and stamp-code glory.",
    summary: "Hall of Fame screen for completed live rewards and weekly winners with stamp code, winner team, and contribution context.",
    primaryAction: "View winners",
    metrics: ["Winner stamp", "Winning team", "Teams participated"],
    sections: ["Winner spotlight", "Past reward cards", "Contribution detail", "Share proof"],
    apiActions: ["GET /rewards/hall-of-fame", "GET /leaderboards/winners?type=live_reward"],
    integrationNotes: ["Hall of Fame is created when rewards rotate and random winning stamp is drawn.", "Past winners endpoint supports live_reward, weekly_team, and weekly_member."],
    qaChecks: ["No completed rewards state works.", "Long team names truncate safely.", "Winner code is copyable."],
    accent: "yellow",
  },
  {
    id: "CB-17",
    stitchScreenId: "9e33eec3c900406aba4b21f792d68006",
    title: "Refined Ranks Hub: Home",
    slug: "ranks-hub-home",
    category: "Ranks",
    route: "/community/leaderboards",
    headline: "Leaderboard home for live reward, weekly teams, and weekly members.",
    summary: "A compact ranks hub with tabs for all three ranking surfaces and current-user position.",
    primaryAction: "Open ranks",
    metrics: ["Live reward", "Weekly teams", "Weekly members"],
    sections: ["Rank tabs", "My position", "Top three podium", "Movement indicators"],
    apiActions: ["GET /leaderboards/live-reward", "GET /leaderboards/weekly-teams", "GET /leaderboards/weekly-members"],
    integrationNotes: ["Live reward ranks teams by current live reward stamps.", "Weekly leaderboards rotate Sunday-Saturday."],
    qaChecks: ["All tabs have loading and empty states.", "Rank ties render consistently.", "Podium order is stable."],
    accent: "cyan",
  },
  {
    id: "CB-18",
    stitchScreenId: "37b4c594d09649b396638623de49dfd0",
    title: "Ranks Hub: Live Reward & Sovereign Integration",
    slug: "ranks-hub-live-reward",
    category: "Ranks",
    route: "/community/leaderboards?tab=live",
    headline: "Live reward leaderboard with sovereign winner mechanics.",
    summary: "Expanded live leaderboard that explains random winning stamp mechanics while showing current team stamp totals.",
    primaryAction: "Track live reward",
    metrics: ["Team stamps", "Winning code", "Reward timer"],
    sections: ["Live reward card", "Team ranking", "Winning mechanics", "Countdown"],
    apiActions: ["GET /leaderboards/live-reward", "GET /rewards/live"],
    integrationNotes: ["Winner is determined by the team that owns the randomly announced winning stamp code after countdown.", "Show mechanics copy to avoid implying highest stamps always wins."],
    qaChecks: ["Mechanics copy is visible.", "Countdown handles expired reward.", "Team rows show current-user team highlight."],
    accent: "purple",
  },
  {
    id: "CB-19",
    stitchScreenId: "364cd5ce03404877b5f7a598b366f3a7",
    title: "Top Operatives: Weekly Rewards Integrated",
    slug: "top-operatives-weekly",
    category: "Ranks",
    route: "/community/leaderboards?tab=weekly-members",
    headline: "Weekly individual leaderboard for top stamp earners.",
    summary: "An esports-style member ranking page with top operatives, weekly reward ties, and personal next-step CTA.",
    primaryAction: "Climb ranking",
    metrics: ["Weekly stamps", "Member rank", "Reward tie-in"],
    sections: ["Top operative hero", "Member rows", "Reward context", "My next task"],
    apiActions: ["GET /leaderboards/weekly-members", "GET /leaderboards/winners?type=weekly_member"],
    integrationNotes: ["Leaderboard #3 ranks individual users by reward stamps in the current week.", "Past weekly member winners are queried by type=weekly_member."],
    qaChecks: ["My row stays visible.", "Past winner cards handle missing avatar.", "Week reset messaging is clear."],
    accent: "orange",
  },
  {
    id: "CB-20",
    stitchScreenId: "901d47bf81584cdd8c9a41acc1c2c24b",
    title: "Chat List: Messages Hub",
    slug: "chat-list",
    category: "Chat",
    route: "/community/conversations",
    headline: "Messages hub for marketplace, service, and squad threads.",
    summary: "Chat list with latest messages, unread state, post context, and fast access to one-to-one conversations.",
    primaryAction: "Open message",
    metrics: ["Unread", "Post context", "Realtime"],
    sections: ["Thread search", "Conversation cards", "Latest message", "Post chip"],
    apiActions: ["GET /community/conversations", "GET /community/conversations/{conversation}/realtime-config"],
    integrationNotes: ["Marketplace/service one-to-one chats use feed conversation realtime config.", "Team chat has a separate private-team channel."],
    qaChecks: ["Empty inbox state links to feed.", "Latest message timestamps are readable.", "Unread badge is accessible."],
    accent: "cyan",
  },
  {
    id: "CB-21",
    stitchScreenId: "b8e602e5e8d24eb5b9f48b94b032d97f",
    title: "Conversation: One-to-One Chat",
    slug: "conversation-one-to-one",
    category: "Chat",
    route: "/community/conversations/[id]",
    headline: "Direct buyer-seller chat with post context locked in.",
    summary: "Conversation detail screen with message bubbles, post summary, send box, and realtime-ready state.",
    primaryAction: "Send message",
    metrics: ["Private channel", "Message history", "Post card"],
    sections: ["Post header", "Message stack", "Composer", "Realtime status"],
    apiActions: ["GET /community/conversations/{conversation}/messages", "POST /community/conversations/{conversation}/messages", "GET /community/conversations/{conversation}/realtime-config"],
    integrationNotes: ["Subscribe to private-feed.conversation.{id} and listen for conversation.message.", "Send body as JSON with a required body field."],
    qaChecks: ["Empty body cannot send.", "New messages append after mutation.", "Long messages wrap in bubbles."],
    accent: "purple",
  },
  {
    id: "CB-22",
    stitchScreenId: "ddac4f5469204a49b69301b75ecee055",
    title: "Squad Chat: Text & Feed Sharing",
    slug: "squad-chat",
    category: "Chat",
    route: "/community-build/squad-chat",
    headline: "Private team chat for text, system events, polls, updates, and feed sharing.",
    summary: "Team chat interface with system messages, admin updates, event cards, poll cards, and shared community posts.",
    primaryAction: "Message squad",
    metrics: ["Team channel", "Polls", "System events"],
    sections: ["Team header", "Message timeline", "Poll/event cards", "Composer"],
    apiActions: ["GET /teams/{team}/messages", "POST /teams/{team}/messages", "POST /teams/{team}/polls", "POST /teams/{team}/events", "POST /teams/{team}/updates"],
    integrationNotes: ["Team chat listens on private-team.{id} for .chat.message.", "Chat push notifications skip the sender and are throttled."],
    qaChecks: ["System messages render distinct style.", "Poll votes update local state.", "Read marker calls mark-read endpoint."],
    accent: "yellow",
  },
  {
    id: "CB-23",
    stitchScreenId: "c437cc4c475d41a48ede82bcae613c3e",
    title: "Stamp Wallet: Earning History & Ledger",
    slug: "stamp-wallet-ledger",
    category: "Wallet",
    route: "/community/stamps",
    headline: "Reward stamp ledger with history, winners, and activity source.",
    summary: "Wallet screen for earned reward stamps, feed stamp activity, winner stamps, and transaction-like history.",
    primaryAction: "Review stamps",
    metrics: ["Reward stamps", "Winner stamps", "Activity"],
    sections: ["Balance hero", "Reward filter", "Ledger rows", "Winner badge"],
    apiActions: ["GET /community/my-stamps-activity", "GET /rewards/my-stamps?reward_id={id}", "GET /api/v1/stamps"],
    integrationNotes: ["Existing stamps endpoint now includes reward_stamps and winner_stamps.", "Feed stamp activity groups by team and reward."],
    qaChecks: ["Ledger handles pagination.", "Winner stamp is visually distinct.", "Reward filter works with no selected reward."],
    accent: "orange",
  },
  {
    id: "CB-24",
    stitchScreenId: "cbf45e51151548c2a249e2722553c9e5",
    title: "Profile: My Transmissions & Boosting",
    slug: "profile-transmissions-boosting",
    category: "Profile",
    route: "/community-build/profile",
    headline: "Personal community profile for posts, boosts, submissions, and rank movement.",
    summary: "Profile page that combines the user's transmissions, boost history, task submissions, stamps, and team identity.",
    primaryAction: "View profile",
    metrics: ["My posts", "Boosts", "Submissions"],
    sections: ["Identity card", "Transmission feed", "Boost ledger", "Submission history"],
    apiActions: ["GET /community/feed?tab=mine", "GET /rewards/{reward}/my-submissions", "GET /community/my-stamps-activity"],
    integrationNotes: ["My feed tab supplies authored posts.", "Submission history exposes task type, payload, review state, and awarded stamps."],
    qaChecks: ["Private data is scoped to authenticated user.", "Rejected submissions show status.", "Boosted posts show expiry."],
    accent: "cyan",
  },
];

export const COMMUNITY_BUILD_CATEGORIES: CommunityBuildCategory[] = [
  "Feed",
  "Create",
  "Teams",
  "Rewards",
  "Ranks",
  "Chat",
  "Wallet",
  "Profile",
];

export function getCommunityBuildScreen(slug: string): CommunityBuildScreen | undefined {
  return COMMUNITY_BUILD_SCREENS.find((screen) => screen.slug === slug);
}
